services:
    tabby:
        build: .
        restart: always
        ports:
        - 9090:80
        environment:
        - DATABASE_URL=${DATABASE_URL}
        - PORT=80
        - DEBUG=False
        - DOCKERIZE_ARGS="-wait tcp://45.84.197.30:3306 -timeout 60s"
        # - APP_DIST_STORAGE="file:///app-dist"
